name: Auto Bump Build Number

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: macos-latest

    steps:
      - name: Skip bump if commit is already a bump
        if: "!startsWith(github.event.head_commit.message || '', 'chore: bump build number')"
        run: echo "Proceeding with build bump..."

      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Count commits
        id: commit_count
        run: echo "count=$(git rev-list --count HEAD)" >> "$GITHUB_OUTPUT"

      - name: Bump build number via agvtool
        run: |
          cd loook
          xcrun agvtool new-version -all ${{ steps.commit_count.outputs.count }}
          cd ..

      - name: Commit & push bumped version
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add loook/loook/loook.xcodeproj/project.pbxproj
          git commit -m "chore: bump build number to ${{ steps.commit_count.outputs.count }}" || echo "No changes to commit"
          git push
