name: Auto Bump Build Number

on:
  push:
    branches:
      - main

jobs:
  bump:
    name: Bump build number via agvtool
    runs-on: macos-latest
    if: "!startsWith(github.event.head_commit.message || '', 'chore: bump build number')"

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump build number
        run: |
          cd loook
          agvtool bump -all

      - name: Commit & push bumped version
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: bump build number"
          git push
